---
- hosts: webserver
  remote_user: jenkins
  become: true
  become_method: sudo
  tasks:
    - name: Install pip
      yum: name=python-pip state=present
    - name: install docker-py package
      pip: name=docker-py
    - name: run the site in a docker container
      docker_container:
        name: tomcat
        image: shruthi1/nodejs-1:12
        state: started
        ports:
         - "8082:8080"
